// Generated by CoffeeScript 1.6.2
(function() {
  var fs, loadDir, _,
    _this = this;

  _ = require('underscore');

  fs = require('fs');

  module.exports = loadDir = function() {
    return console.log('hi');
  };

}).call(this);
