// Generated by CoffeeScript 1.6.3
(function() {
  var CoffeeScript, Directory, File, child, colors, extension, fs, loaddir, trim_ext, _, _ref;

  _ = require('underscore');

  fs = require('fs');

  child = require('child_process');

  CoffeeScript = require('coffee-script');

  _ref = require('./string_helper'), extension = _ref.extension, trim_ext = _ref.trim_ext;

  colors = require('colors');

  File = require('./file_class.coffee');

  Directory = require('./directory_class.coffee');

  module.exports = loaddir = function(options) {
    var directory;
    if (options == null) {
      options = {};
    }
    if (options.debug) {
      console.log('Loaddir debug mode!'.zebra);
    }
    if (options.watch_handler == null) {
      options.watch_handler = options.on_change;
    }
    if (options.extension && options.extension[0] === '.') {
      options.extension = options.extension.substring(1);
    }
    if ('/' === _.last(options.path)) {
      options.path = options.path.slice(0, -1);
    }
    options.top = true;
    options.output = {};
    directory = new Directory(options);
    if (options.expose_hooks) {
      return directory;
    } else {
      return options.output;
    }
  };

}).call(this);
